schema:
  - "http://localhost:3000/api/graphql"
documents:
  - "./src/graphql/**/*.ts"
generates:
  ./generated/graphql.ts:
    plugins:
      - typescript
      - typescript-operations
      - typescript-react-apollo
